import AxeBuilder from '@axe-core/playwright'
import { expect,test } from '@playwright/test'
test('accessible English page fits the viewport and supports keyboard anchors',async({page})=>{
 await page.goto('/')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
 expect((await new AxeBuilder({page}).analyze()).violations).toEqual([])
 await expect(page).toHaveTitle('Acrazie — Software Engineer & AI Engineer')
 await expect(page.locator('html')).toHaveAttribute('lang','en')
 await page.keyboard.press('Tab');await expect(page.getByRole('link',{name:'Skip to content'})).toBeFocused()
 await page.keyboard.press('Enter');await expect(page.locator('#main')).toBeFocused()
 await page.getByRole('link',{name:'Contact',exact:true}).click();await expect(page).toHaveURL(/#contact$/)
})
test('no JavaScript still exposes every section and graph',async({browser,baseURL})=>{
 const context=await browser.newContext({javaScriptEnabled:false}),page=await context.newPage()
 await page.goto(baseURL!)
 for(const name of ['Capabilities','Selected work','Contact']) await expect(page.getByRole('region',{name})).toBeVisible()
 await expect(page.getByTestId('execution-graph-fallback')).toBeVisible()
 await context.close()
})
test('living hero draws continuously while offscreen journey rests and reacts to native scroll',async({page})=>{
 await page.goto('/')
 const graph=page.getByTestId('execution-graph-canvas')
 await graph.scrollIntoViewIfNeeded()
 await expect(graph).toHaveAttribute('data-ready','true')
 await expect(graph).toHaveAttribute('data-phase','settled',{timeout:12000});await page.waitForTimeout(200)
 const count=async()=>Number(await graph.getAttribute('data-draw-count'))
 const idle=await count();await page.waitForTimeout(1000);expect(await count()-idle).toBeGreaterThan(1)
 await page.evaluate(()=>window.scrollBy({top:120,behavior:'instant'}))
 await expect.poll(count).toBeGreaterThan(idle)
 await page.evaluate(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'instant'}))
 await expect(graph).toHaveAttribute('data-word','1')
 const off=await count();await page.waitForTimeout(600);expect(await count()).toBe(off)
})
test('reduced motion is static even after pointer and scroll input',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 const graph=page.getByTestId('execution-graph-canvas')
 await graph.scrollIntoViewIfNeeded();await expect(graph).toHaveAttribute('data-motion','reduced')
 await expect(page.getByTestId('execution-graph-fallback')).toBeVisible();await expect(page.getByTestId('logo-particles')).toHaveCSS('visibility','hidden');await page.waitForTimeout(200)
 const before=await graph.getAttribute('data-draw-count')
 await page.mouse.move(400,400);await page.evaluate(()=>window.scrollBy({top:50,behavior:'instant'}));await page.waitForTimeout(600)
 expect(await graph.getAttribute('data-draw-count')).toBe(before)
})
test('context loss retains usable fallback and contact',async({page})=>{
 await page.goto('/')
 const graph=page.getByTestId('execution-graph-canvas')
 await expect(graph).toHaveAttribute('data-ready','true')
 await graph.locator('canvas').evaluate(c=>c.dispatchEvent(new Event('webglcontextlost',{cancelable:true})))
 await expect(graph).toHaveCount(0)
 await expect(page.getByTestId('execution-graph-fallback')).toBeVisible()
 await page.getByRole('link',{name:'Contact',exact:true}).click();await expect(page).toHaveURL(/#contact$/)
})
test('hot reduced motion, pause and hidden clear impulses without remounting the canvas',async({page})=>{
 await page.goto('/');const graph=page.getByTestId('execution-graph-canvas'),host=page.getByTestId('logo-particles')
 await expect(graph).toHaveAttribute('data-phase','settled',{timeout:15000})
 const node=await graph.locator('canvas').elementHandle()
 for(const mode of ['reduce','pause','hidden']){
  if(mode==='reduce')await page.emulateMedia({reducedMotion:'reduce'})
  if(mode==='pause')await page.getByRole('button',{name:'Pause animation'}).click()
  if(mode==='hidden')await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'hidden'});document.dispatchEvent(new Event('visibilitychange'))})
  await expect(host).toHaveCSS('visibility','hidden');await expect(page.getByTestId('execution-graph-fallback')).toBeVisible()
  await page.waitForTimeout(100);const count=await graph.getAttribute('data-draw-count')
  await page.evaluate(()=>scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));await page.waitForTimeout(150)
  expect(await graph.getAttribute('data-draw-count')).toBe(count);await expect(page.getByTestId('particle-word')).not.toHaveCSS('color','rgba(0, 0, 0, 0)')
  if(mode==='reduce')await page.emulateMedia({reducedMotion:'no-preference'})
  if(mode==='pause')await page.getByRole('button',{name:'Resume animation'}).click()
  if(mode==='hidden')await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'visible'});document.dispatchEvent(new Event('visibilitychange'))})
  await expect(graph).toHaveAttribute('data-word','1');await expect(host).toHaveCSS('visibility','visible')
  expect(await node!.evaluate(c=>c===document.querySelector('canvas'))).toBe(true)
  await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await expect(graph).toHaveAttribute('data-split','0')
 }
})
test('font failure keeps a semantic static word and disables word interaction',async({page})=>{
 await page.addInitScript(()=>{document.fonts.load=()=>Promise.reject(new Error('test font failure'))})
 await page.goto('/');const graph=page.getByTestId('execution-graph-canvas')
 await expect(graph).toHaveAttribute('data-ready','true')
 await page.evaluate(()=>scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));await page.waitForTimeout(250)
 await expect(page.getByTestId('particle-word')).toBeVisible();await expect(page.getByTestId('particle-word')).not.toHaveCSS('color','rgba(0, 0, 0, 0)')
 await expect(page.getByRole('button',{name:'Animate MAYEUL'})).toHaveCount(0)
 await expect(graph).toHaveAttribute('data-word','0')
})
