import AxeBuilder from '@axe-core/playwright'
import { expect,test } from '@playwright/test'
test('accessible French page fits the viewport, switches language, and supports keyboard anchors',async({page,isMobile})=>{
 await page.goto('/')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
 expect((await new AxeBuilder({page}).analyze()).violations).toEqual([])
 await expect(page).toHaveTitle('Mayeul — Software Engineer · AI Engineer')
 await expect(page.locator('html')).toHaveAttribute('lang','fr')
 await page.keyboard.press('Tab');await expect(page.getByRole('link',{name:'Aller au contenu'})).toBeFocused()
 await page.keyboard.press('Enter');await expect(page.locator('#main')).toBeFocused()
 await page.getByRole('link',{name:'Entrer dans le portfolio'}).click();await expect(page).toHaveURL(/#about$/)
 await page.getByRole('button',{name:'Langue : français. Passer en anglais'}).click()
 await expect(page.locator('html')).toHaveAttribute('lang','en')
 if(isMobile)await expect(page.getByRole('navigation',{name:'Primary navigation'})).toBeHidden()
 else await expect(page.getByRole('navigation',{name:'Primary navigation'})).toBeVisible()
})
test('no JavaScript still exposes every section and graph',async({browser,baseURL})=>{
 const context=await browser.newContext({javaScriptEnabled:false}),page=await context.newPage()
 await page.goto(baseURL!)
 for(const name of ['Expertise en mouvement','Travail sélectionné','Construisons quelque chose de fiable.']) await expect(page.getByRole('region',{name})).toBeVisible()
 await expect(page.getByTestId('execution-graph-fallback')).toBeVisible()
 await context.close()
})
test('living hero draws continuously while offscreen journey rests and reacts to native scroll',async({page})=>{
 await page.goto('/')
 const graph=page.getByTestId('execution-graph-canvas')
 await graph.scrollIntoViewIfNeeded()
 await expect(graph).toHaveAttribute('data-ready','true')
 await expect(graph).toHaveAttribute('data-phase','settled',{timeout:12000});await page.waitForTimeout(200)
 const count=async()=>Number(await graph.getAttribute('data-draw-count'))
 const idle=await count();await page.waitForTimeout(1000);expect(await count()-idle).toBeGreaterThan(1)
 await page.evaluate(()=>window.scrollBy({top:120,behavior:'instant'}))
 await expect.poll(count).toBeGreaterThan(idle)
 await page.evaluate(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'instant'}))
 await expect(graph).toHaveAttribute('data-word','1')
 const off=await count();await page.waitForTimeout(600);expect(await count()).toBe(off)
})
test('reduced motion is static even after pointer and scroll input',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 await expect(page.getByTestId('execution-graph-canvas')).toHaveCount(0)
 await expect(page.getByTestId('execution-graph-fallback')).toBeVisible();await expect(page.getByTestId('logo-particles')).toHaveCSS('visibility','hidden');await page.waitForTimeout(200)
 await page.mouse.move(400,400);await page.evaluate(()=>window.scrollBy({top:50,behavior:'instant'}));await page.waitForTimeout(600)
 await expect(page.getByTestId('execution-graph-canvas')).toHaveCount(0)
})
test('context loss retains usable fallback and contact',async({page})=>{
 await page.goto('/')
 const graph=page.getByTestId('execution-graph-canvas')
 await expect(graph).toHaveAttribute('data-ready','true')
 await graph.locator('canvas').evaluate(c=>c.dispatchEvent(new Event('webglcontextlost',{cancelable:true})))
 await expect(graph).toHaveCount(0)
 await expect(page.getByTestId('execution-graph-fallback')).toBeVisible()
 await page.locator('#contact').scrollIntoViewIfNeeded()
 await expect(page.getByRole('link',{name:'Envoyer un email'})).toBeVisible()
})
test('pause, hot reduced motion, and hidden pages stop the scene and preserve fallbacks',async({page})=>{
 await page.goto('/');const host=page.getByTestId('logo-particles')
 await expect(page.getByTestId('execution-graph-canvas')).toHaveAttribute('data-phase','settled',{timeout:15000})
 await page.getByRole('button',{name:'Mettre l’animation en pause'}).click()
 await expect(page.getByRole('button',{name:'Reprendre l’animation'})).toBeVisible()
 const pausedCount=await page.getByTestId('execution-graph-canvas').getAttribute('data-draw-count');await page.waitForTimeout(200)
 expect(await page.getByTestId('execution-graph-canvas').getAttribute('data-draw-count')).toBe(pausedCount)
 await page.getByRole('button',{name:'Reprendre l’animation'}).click()
 await expect(host).toHaveCSS('visibility','visible')
 await page.emulateMedia({reducedMotion:'reduce'})
 await expect(page.getByTestId('execution-graph-canvas')).toHaveCount(0)
 await expect(page.getByTestId('execution-graph-fallback')).toBeVisible()
 await page.emulateMedia({reducedMotion:'no-preference'})
 await expect(page.getByTestId('execution-graph-canvas')).toHaveAttribute('data-ready','true')
 await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'hidden'});document.dispatchEvent(new Event('visibilitychange'))})
 await expect(host).toHaveCSS('visibility','visible')
 const count=await page.getByTestId('execution-graph-canvas').getAttribute('data-draw-count');await page.waitForTimeout(200)
 expect(await page.getByTestId('execution-graph-canvas').getAttribute('data-draw-count')).toBe(count)
})
test('font failure keeps a semantic static word and disables word interaction',async({page})=>{
 await page.addInitScript(()=>{document.fonts.load=()=>Promise.reject(new Error('test font failure'))})
 await page.goto('/');const graph=page.getByTestId('execution-graph-canvas')
 await expect(graph).toHaveAttribute('data-ready','true')
 await page.evaluate(()=>scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));await page.waitForTimeout(250)
 await expect(page.getByTestId('particle-word')).toBeVisible();await expect(page.getByTestId('particle-word')).not.toHaveCSS('color','rgba(0, 0, 0, 0)')
 await expect(page.getByRole('button',{name:'Animate MAYEUL'})).toHaveCount(0)
 await expect(graph).toHaveAttribute('data-word','0')
})
