import AxeBuilder from '@axe-core/playwright'
import { expect,test } from '@playwright/test'
test('accessible English page fits the viewport and supports keyboard anchors',async({page})=>{
 await page.goto('/')
 expect(await page.evaluate(()=>document.documentElement.scrollWidth-document.documentElement.clientWidth)).toBeLessThanOrEqual(1)
 expect((await new AxeBuilder({page}).analyze()).violations).toEqual([])
 await expect(page).toHaveTitle('Acrazie — Software Engineer & AI Engineer')
 await expect(page.locator('html')).toHaveAttribute('lang','en')
 await page.keyboard.press('Tab');await expect(page.getByRole('link',{name:'Skip to content'})).toBeFocused()
 await page.keyboard.press('Enter');await expect(page.locator('#main')).toBeFocused()
 await page.getByRole('link',{name:'Contact',exact:true}).click();await expect(page).toHaveURL(/#contact$/)
})
test('no JavaScript still exposes every section and graph',async({browser,baseURL})=>{
 const context=await browser.newContext({javaScriptEnabled:false}),page=await context.newPage()
 await page.goto(baseURL!)
 for(const name of ['Capabilities','Selected work','Contact']) await expect(page.getByRole('region',{name})).toBeVisible()
 await expect(page.getByTestId('execution-graph-fallback')).toBeVisible()
 await context.close()
})
test('draw requests settle when idle and stop off-screen',async({page})=>{
 await page.goto('/')
 const graph=page.getByTestId('execution-graph-canvas')
 await graph.scrollIntoViewIfNeeded()
 await expect(graph).toHaveAttribute('data-ready','true')
 await page.waitForTimeout(500)
 const count=async()=>Number(await graph.getAttribute('data-draw-count'))
 const idle=await count();await page.waitForTimeout(1000);expect(await count()-idle).toBeLessThanOrEqual(1)
 await page.evaluate(()=>window.scrollBy({top:120,behavior:'instant'}))
 await expect.poll(count).toBeGreaterThan(idle)
 await page.evaluate(()=>window.scrollTo({top:document.body.scrollHeight,behavior:'instant'}))
 await page.waitForTimeout(600);const off=await count();await page.waitForTimeout(600);expect(await count()).toBe(off)
})
test('reduced motion is static even after pointer and scroll input',async({page})=>{
 await page.emulateMedia({reducedMotion:'reduce'})
 await page.goto('/')
 const graph=page.getByTestId('execution-graph-canvas')
 await graph.scrollIntoViewIfNeeded();await expect(graph).toHaveAttribute('data-motion','reduced')
 await expect(graph).toHaveAttribute('data-ready','true');await page.waitForTimeout(500)
 const before=await graph.getAttribute('data-draw-count')
 await page.mouse.move(400,400);await page.evaluate(()=>window.scrollBy({top:50,behavior:'instant'}));await page.waitForTimeout(600)
 expect(await graph.getAttribute('data-draw-count')).toBe(before)
})
test('context loss retains usable fallback and contact',async({page})=>{
 await page.goto('/')
 const graph=page.getByTestId('execution-graph-canvas')
 await expect(graph).toHaveAttribute('data-ready','true')
 await graph.locator('canvas').evaluate(c=>c.dispatchEvent(new Event('webglcontextlost',{cancelable:true})))
 await expect(graph).toHaveCount(0)
 await expect(page.getByTestId('execution-graph-fallback')).toBeVisible()
 await page.getByRole('link',{name:'Contact',exact:true}).click();await expect(page).toHaveURL(/#contact$/)
})
