import { expect,test } from '@playwright/test'
import {pixels} from './particle-pixels'
test('living ink moves without input, parallax follows depth, and scroll interrupts the opening',async({page,isMobile},info)=>{
 await page.goto('/');const graph=page.getByTestId('execution-graph-canvas')
 await expect(graph).toHaveAttribute('data-phase','intro')
 await page.evaluate(()=>scrollTo({top:document.documentElement.scrollHeight/2,behavior:'instant'}))
 await expect(graph).toHaveAttribute('data-phase','settled');await expect(graph).toHaveAttribute('data-split','1')
 await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await expect(graph).toHaveAttribute('data-split','0')
 const canvas=graph.locator('canvas'),before=await canvas.screenshot({scale:'css'})
 await page.waitForTimeout(900);const after=await canvas.screenshot({scale:'css'})
 expect((await pixels(page,before,after)).changed).toBeGreaterThan(50)
 await info.attach('living-before',{body:before,contentType:'image/png'});await info.attach('living-after',{body:after,contentType:'image/png'})
 if(!isMobile){
  const size=page.viewportSize()!;await page.mouse.move(size.width*.7,size.height*.45);await page.waitForTimeout(700)
  expect(JSON.parse((await graph.getAttribute('data-parallax'))!).x).toBeGreaterThan(.2)
 }
})
test('finite depth intro, pause, resume, then living logo frames',async({page})=>{
 await page.goto('/')
 const graph=page.getByTestId('execution-graph-canvas')
 await expect(graph).toHaveAttribute('data-phase','intro')
 const count=async()=>Number(await graph.getAttribute('data-draw-count'))
 const first=await count();await page.waitForTimeout(200);expect(await count()).toBeGreaterThan(first)
 await page.getByRole('button',{name:'Pause animation'}).click()
 await page.waitForTimeout(150)
 const stopped=await count();await page.waitForTimeout(350);expect(await count()).toBe(stopped)
 await page.getByRole('button',{name:'Resume animation'}).click()
 await expect(graph).toHaveAttribute('data-phase','settled',{timeout:12000})
 await page.waitForTimeout(150);const settled=await count()
 await page.waitForTimeout(350);expect(await count()).toBeGreaterThan(settled)
})
test('hidden tab freezes the intro clock and resumes without a jump',async({page})=>{
 await page.goto('/')
 const graph=page.getByTestId('execution-graph-canvas')
 await expect(graph).toHaveAttribute('data-phase','intro')
 await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'hidden'});document.dispatchEvent(new Event('visibilitychange'))})
 await page.waitForTimeout(150)
 const progress=await graph.getAttribute('data-intro')
 await page.waitForTimeout(500);expect(await graph.getAttribute('data-intro')).toBe(progress)
 await page.evaluate(()=>{Object.defineProperty(document,'visibilityState',{configurable:true,value:'visible'});document.dispatchEvent(new Event('visibilitychange'))})
 await expect(graph).toHaveAttribute('data-phase','settled',{timeout:12000})
})
