import {expect,test} from '@playwright/test'
test('same viewport canvas splits into both gutters and reaches the real final word',async({page})=>{
 await page.goto('/')
 const graph=page.getByTestId('execution-graph-canvas')
 await expect(graph).toHaveAttribute('data-phase','settled',{timeout:15000})
 const canvas=await graph.locator('canvas').elementHandle()
 await page.evaluate(()=>scrollTo({top:document.documentElement.scrollHeight/2,behavior:'instant'}))
 await expect(graph).toHaveAttribute('data-split','1')
 await expect(graph).toHaveAttribute('data-word','0')
 expect(await canvas!.evaluate(c=>c===document.querySelector('canvas'))).toBe(true)
 await page.evaluate(()=>scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}))
 await expect(graph).toHaveAttribute('data-word','1')
 await expect(page.getByRole('button',{name:'Animate MAYEUL'})).toHaveCount(0)
 await expect(page.getByTestId('particle-word')).toHaveCSS('opacity','1')
 const word=await page.getByTestId('particle-word').boundingBox();expect(word!.y).toBeGreaterThan(0);expect(word!.y+word!.height).toBeLessThan(page.viewportSize()!.height)
 await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await expect(graph).toHaveAttribute('data-split','0')
 expect(await canvas!.evaluate(c=>c===document.querySelector('canvas'))).toBe(true)
})
import {inkPoints,pixels} from './particle-pixels'
test('both rendered gutters remain visible over light and dark sections with no central bleed',async({page})=>{
 await page.goto('/');const graph=page.getByTestId('execution-graph-canvas')
 await expect(graph).toHaveAttribute('data-phase','settled',{timeout:15000})
 for(const selector of ['#capabilities','#work']){
  await page.locator(selector).evaluate(el=>scrollTo({top:el.getBoundingClientRect().top+scrollY+100,behavior:'instant'}))
  // Reveal lasts .55s plus nested delays; compare only settled DOM pixels.
  await expect(graph).toHaveAttribute('data-split','1');await page.waitForTimeout(850)
  const canvas=graph.locator('canvas'),visible=await canvas.screenshot({scale:'css'})
  await canvas.evaluate(el=>el.style.visibility='hidden');const hidden=await page.screenshot({scale:'css'});await canvas.evaluate(el=>el.style.visibility='')
  const metric=await pixels(page,hidden,visible)
  expect(metric.left).toBeGreaterThan(20);expect(metric.right).toBeGreaterThan(20);expect(metric.center).toBe(0)
 }
})
test('automatic finale settles to readable type; ink, blanks and keyboard cannot trigger an effect',async({page})=>{
 await page.goto('/');const graph=page.getByTestId('execution-graph-canvas')
 await expect(graph).toHaveAttribute('data-ready','true')
 await page.evaluate(()=>scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}))
 await expect(graph).toHaveAttribute('data-word-target','1')
 await expect.poll(()=>graph.getAttribute('data-word').then(Number)).toBeGreaterThan(0)
 await expect(graph).toHaveAttribute('data-word','1')
 await expect(page.getByTestId('particle-word')).toHaveCSS('opacity','1')
 await expect(page.getByRole('button',{name:'Animate MAYEUL'})).toHaveCount(0)
 await expect(page.getByTestId('particle-word')).toHaveText('MAYEUL')
 const canvas=graph.locator('canvas'),baseline=await canvas.screenshot({scale:'css'}),points=await inkPoints(page)
 const count=await graph.getAttribute('data-draw-count')
 for(const p of [points.blank,...points.ink])await page.mouse.click(p.x,p.y)
 await page.keyboard.press('Enter')
 await page.getByTestId('logo-particles').evaluate(el=>el.dispatchEvent(new Event('particleburst')))
 await page.waitForTimeout(150)
 expect(await graph.getAttribute('data-draw-count')).toBe(count)
 expect((await pixels(page,baseline,await canvas.screenshot({scale:'css'}))).changed).toBe(0)
})
test('actual section boundaries drive different spatial states in both scroll directions',async({page})=>{
 await page.goto('/');const graph=page.getByTestId('execution-graph-canvas')
 await expect(graph).toHaveAttribute('data-ready','true')
 const states:number[]=[]
 for(const selector of ['#work','#capabilities','#contact','#capabilities','#work']){
  await page.locator(selector).evaluate(el=>scrollTo({top:el.getBoundingClientRect().top+scrollY-innerHeight*.4,behavior:'instant'}))
  await expect.poll(()=>graph.getAttribute('data-turn').then(Number)).toBeGreaterThan(.5)
  await page.waitForTimeout(100)
  states.push(Number(await graph.getAttribute('data-travel')))
 }
 expect(states[1]).toBeGreaterThan(states[0]);expect(states[2]).toBeGreaterThan(states[1])
 expect(states[3]).toBeCloseTo(states[1],4);expect(states[4]).toBeCloseTo(states[0],4)
})
test('resize, anchor entry and reverse scroll keep identity and return to the isolated living baseline',async({page})=>{
 await page.goto('/#contact');const graph=page.getByTestId('execution-graph-canvas')
 await expect(graph).toHaveAttribute('data-phase','settled',{timeout:15000})
 await graph.evaluate(e=>(e as HTMLElement).dataset.lifeTime='0')
 const canvas=graph.locator('canvas'),node=await canvas.elementHandle(),generation=await graph.getAttribute('data-resource-generation')
 for(const [width,height] of [[393,852],[320,568],[1440,1000],[2750,1510]]){
  await page.setViewportSize({width,height});await page.evaluate(()=>scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}))
  await expect(graph).toHaveAttribute('data-word','1')
  await expect(page.getByRole('button',{name:'Animate MAYEUL'})).toHaveCount(0)
  expect(await graph.getAttribute('data-resource-generation')).toBe(generation)
  expect(await node!.evaluate(c=>c===document.querySelector('canvas'))).toBe(true)
 }
 await page.setViewportSize({width:1440,height:1000});await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await expect(graph).toHaveAttribute('data-split','0');await page.waitForTimeout(150)
 const baseline=await canvas.screenshot({scale:'css'})
 await page.evaluate(()=>scrollTo({top:document.documentElement.scrollHeight,behavior:'instant'}));await expect(graph).toHaveAttribute('data-word','1')
 await page.getByTestId('particle-word').click()
 await page.evaluate(()=>scrollTo({top:0,behavior:'instant'}));await expect(graph).toHaveAttribute('data-split','0');await page.waitForTimeout(150)
 expect((await pixels(page,baseline,await canvas.screenshot({scale:'css'}))).changed).toBe(0)
 await expect(graph).toHaveAttribute('data-push-energy','0')
})
