export type Locale = 'fr' | 'en'

export const portfolio = {
  contentStatus: 'draft',
  displayName: 'Mayeul',
  githubHandle: 'acrazie',
  role: 'Software Engineer · AI Engineer',
  links: [
    { id: 'github', label: 'GitHub', href: 'https://github.com/acrazie', detail: '@acrazie' },
    { id: 'linkedin', label: 'LinkedIn', href: 'https://www.linkedin.com/in/mayeuld/', detail: '/in/mayeuld' },
    { id: 'skills', label: 'skills.sh', href: 'https://www.skills.sh/acrazie', detail: '/acrazie' },
    { id: 'email', label: 'Email', href: 'mailto:mayeul.desbazeille@gmail.com', detail: 'mayeul.desbazeille@gmail.com' },
  ],
  tools: ['Codex', 'Claude', 'Gemini'],
  project: {
    href: 'https://github.com/acrazie/portfolio-web',
    stack: ['React', 'TanStack Start', 'React Three Fiber', 'GLSL', 'Bun'],
  },
  copy: {
    fr: {
      navigationLabel: 'Navigation principale',
      nav: { about: 'À propos', work: 'Travail', capabilities: 'Expertise', skills: 'Skills', contact: 'Contact' },
      language: { label: 'Langue : français. Passer en anglais', short: 'FR', other: 'EN' },
      hero: {
        title: 'Mayeul — Software Engineer et AI Engineer',
        statement: 'Des logiciels fiables. Une IA réellement utile.',
        body: 'Je transforme une veille quotidienne sur les agents, modèles et outils IA en systèmes testables pour l’entreprise.',
        explore: 'Entrer dans le portfolio',
        instrument: 'Champ actif',
        instrumentStatus: 'Actif',
        signal: 'Pointeur : réfraction · Scroll : séparation',
      },
      about: {
        title: 'Ingénierie logicielle, augmentée avec discernement.',
        body: 'J’utilise Codex, Claude et Gemini dans plusieurs environnements agentiques. Je suis les nouveaux modèles, techniques de compression, plugins et skills pour choisir ce qui améliore réellement le travail logiciel.',
        note: 'Le portfolio reste volontairement factuel : expérience, formation et résultats seront ajoutés après vérification.',
      },
      experience: {
        title: 'Entreprise & parcours',
        status: 'Données en préparation',
        body: 'Entreprise actuelle, rôles et dates ne sont pas encore publiés. Cet espace restera factuel plutôt que d’afficher des informations inventées.',
      },
      education: {
        title: 'Formation',
        status: 'Données en préparation',
        body: 'Établissements, diplômes et dates seront ajoutés après vérification des informations à publier.',
      },
      work: {
        title: 'Travail sélectionné',
        intro: 'Une première preuve vérifiable : ce portfolio et son système graphique vivant.',
        projectTitle: 'Portfolio particulaire vivant',
        projectBody: 'Un symbole WebGL composé de glyphes, animé à la demande, sensible au pointeur et au scroll, avec rendu SSR, repli statique et réduction de mouvement.',
        link: 'Voir le dépôt',
        status: 'Open source',
        provenance: 'Source vérifiable dans le dépôt public.',
        stackLabel: 'Technologies du projet',
        facts: ['Compatible SSR', 'Repli sans animation', 'Rendu à la demande', 'Livraison conteneurisée'],
      },
      capabilities: {
        title: 'Expertise en mouvement',
        intro: 'Trois champs reliés par une même discipline : rendre les décisions observables et le résultat vérifiable.',
        groups: [
          { title: 'Systèmes logiciels', body: 'Architecture, implémentation, tests et décisions techniques.' },
          { title: 'IA appliquée', body: 'Agents, modèles, compression de contexte, plugins et skills intégrés à des workflows utiles.' },
          { title: 'Livraison', body: 'Du prototype à une version construite, testée, conteneurisée et déployable.' },
        ],
      },
      achievements: {
        title: 'Résultats et jalons',
        status: 'Preuves à confirmer',
        body: 'Aucun résultat chiffré ni jalon professionnel ne sera publié sans source vérifiable.',
      },
      tools: {
        title: 'Outils quotidiens',
        intro: 'Une pratique multi-modèle, choisie selon le contexte plutôt qu’un seul fournisseur.',
        detail: 'Codage agentique, exploration, revue et orchestration avec différents harnesses.',
      },
      external: {
        title: 'Skills pour agents IA',
        body: 'Mes skills publics sont regroupés sur skills.sh. Le profil externe reste la source pour leur liste et leur classement actuels.',
        link: 'Explorer le profil skills.sh',
      },
      blog: {
        title: 'Notes de laboratoire',
        status: 'Articles à venir',
        body: 'Modèles, compression, plugins, skills et méthodes de travail agentiques : les futurs articles apparaîtront ici après publication.',
      },
      contact: {
        title: 'Construisons quelque chose de fiable.',
        body: 'Email direct et profils vérifiés. Le chat et la prise de rendez-vous seront ajoutés lorsqu’une destination aura été confirmée.',
        email: 'Envoyer un email',
      },
      pending: 'Contenu en préparation',
      pause: { pause: 'Mettre l’animation en pause', resume: 'Reprendre l’animation', pauseShort: 'Pause', playShort: 'Lecture' },
      footer: 'Software Engineering · Applied AI',
    },
    en: {
      navigationLabel: 'Primary navigation',
      nav: { about: 'About', work: 'Work', capabilities: 'Expertise', skills: 'Skills', contact: 'Contact' },
      language: { label: 'Language: English. Switch to French', short: 'EN', other: 'FR' },
      hero: {
        title: 'Mayeul — Software Engineer and AI Engineer',
        statement: 'Dependable software. AI that proves useful.',
        body: 'I turn daily research into agents, models, and AI tooling into testable systems for enterprise work.',
        explore: 'Enter the portfolio',
        instrument: 'Active field',
        instrumentStatus: 'Live',
        signal: 'Pointer: refraction · Scroll: separation',
      },
      about: {
        title: 'Software engineering, augmented with judgment.',
        body: 'I use Codex, Claude, and Gemini across several agent harnesses. I track new models, compression techniques, plugins, and skills to choose what genuinely improves software work.',
        note: 'This portfolio stays deliberately factual: experience, education, and outcomes will be added after verification.',
      },
      experience: {
        title: 'Company & experience',
        status: 'Record in progress',
        body: 'Current company, roles, and dates are not published yet. This space stays factual rather than displaying invented information.',
      },
      education: {
        title: 'Education',
        status: 'Record in progress',
        body: 'Institutions, qualifications, and dates will be added after the information intended for publication is verified.',
      },
      work: {
        title: 'Selected work',
        intro: 'A first verifiable proof: this portfolio and its living graphic system.',
        projectTitle: 'Living particle portfolio',
        projectBody: 'A WebGL symbol built from glyphs, rendered on demand, responsive to pointer and scroll, with SSR, a static fallback, and reduced-motion support.',
        link: 'View repository',
        status: 'Open source',
        provenance: 'Verifiable source in the public repository.',
        stackLabel: 'Project technologies',
        facts: ['SSR-ready', 'Reduced-motion fallback', 'Demand rendering', 'Container delivery'],
      },
      capabilities: {
        title: 'Expertise in motion',
        intro: 'Three connected fields, one discipline: make decisions observable and results verifiable.',
        groups: [
          { title: 'Software systems', body: 'Architecture, implementation, testing, and technical decisions.' },
          { title: 'Applied AI', body: 'Agents, models, context compression, plugins, and skills integrated into useful workflows.' },
          { title: 'Delivery', body: 'From prototype to a built, tested, containerized, deployable release.' },
        ],
      },
      achievements: {
        title: 'Outcomes and milestones',
        status: 'Evidence to confirm',
        body: 'No metric or professional milestone will be published without verifiable evidence.',
      },
      tools: {
        title: 'Daily tools',
        intro: 'A multi-model practice, chosen for the context rather than one provider.',
        detail: 'Agentic coding, exploration, review, and orchestration across different harnesses.',
      },
      external: {
        title: 'Skills for AI agents',
        body: 'My public skills are collected on skills.sh. The external profile remains the source for their current list and ranking.',
        link: 'Explore skills.sh profile',
      },
      blog: {
        title: 'Lab notes',
        status: 'Articles to come',
        body: 'Models, compression, plugins, skills, and agentic working methods will appear here after publication.',
      },
      contact: {
        title: 'Let’s build something dependable.',
        body: 'Direct email and verified profiles. Chat and booking will appear once a destination is confirmed.',
        email: 'Send an email',
      },
      pending: 'Content in progress',
      pause: { pause: 'Pause animation', resume: 'Resume animation', pauseShort: 'Pause', playShort: 'Play' },
      footer: 'Software Engineering · Applied AI',
    },
  },
} as const
