import * as m from "@/paraglide/messages";
import type { Locale } from "@/paraglide/runtime";

function createSkills(locale: Locale) {
	const opt = { locale };
	return [
		{
			id: "planner",
			slug: "multi-agent-planner-acrazie",
			group: "agents",
			featured: true,
			name: m.skill_planner_name({}, opt),
			description: m.skill_planner_description({}, opt),
			result: m.skill_planner_result({}, opt),
		},
		{
			id: "refiner",
			slug: "skill-refiner-acrazie",
			group: "agents",
			featured: true,
			name: m.skill_refiner_name({}, opt),
			description: m.skill_refiner_description({}, opt),
			result: m.skill_refiner_result({}, opt),
		},
		{
			id: "audit",
			slug: "audit-repository-acrazie",
			group: "repository",
			featured: true,
			name: m.skill_audit_name({}, opt),
			description: m.skill_audit_description({}, opt),
			result: m.skill_audit_result({}, opt),
		},
		{
			id: "modernizer",
			slug: "repo-modernizer-acrazie",
			group: "repository",
			featured: true,
			name: m.skill_modernizer_name({}, opt),
			description: m.skill_modernizer_description({}, opt),
			result: m.skill_modernizer_result({}, opt),
		},
		{
			id: "readme",
			slug: "repository-readme-architect-acrazie",
			group: "repository",
			featured: true,
			name: m.skill_readme_name({}, opt),
			description: m.skill_readme_description({}, opt),
			result: m.skill_readme_result({}, opt),
		},
		{
			id: "canvas",
			slug: "canvas-banner-designer-acrazie",
			group: "visual",
			featured: true,
			name: m.skill_canvas_name({}, opt),
			description: m.skill_canvas_description({}, opt),
			result: m.skill_canvas_result({}, opt),
		},
		{
			id: "icon",
			slug: "svg-icon-designer-acrazie",
			group: "visual",
			featured: true,
			name: m.skill_icon_name({}, opt),
			description: m.skill_icon_description({}, opt),
			result: m.skill_icon_result({}, opt),
		},
		{
			id: "jenkins",
			slug: "jenkins-devops-acrazie",
			group: "delivery",
			featured: true,
			name: m.skill_jenkins_name({}, opt),
			description: m.skill_jenkins_description({}, opt),
			result: m.skill_jenkins_result({}, opt),
		},
		{
			id: "gitship",
			slug: "git-ship-acrazie",
			group: "delivery",
			featured: false,
			name: m.skill_gitship_name({}, opt),
			description: m.skill_gitship_description({}, opt),
			result: null,
		},
		{
			id: "init",
			slug: "github-repo-init-acrazie",
			group: "repository",
			featured: false,
			name: m.skill_init_name({}, opt),
			description: m.skill_init_description({}, opt),
			result: null,
		},
		{
			id: "banner",
			slug: "svg-banner-designer-acrazie",
			group: "visual",
			featured: false,
			name: m.skill_banner_name({}, opt),
			description: m.skill_banner_description({}, opt),
			result: null,
		},
		{
			id: "go",
			slug: "jenkins-go-acrazie",
			group: "delivery",
			featured: false,
			name: m.skill_go_name({}, opt),
			description: m.skill_go_description({}, opt),
			result: null,
		},
		{
			id: "jsts",
			slug: "jenkins-js-ts-acrazie",
			group: "delivery",
			featured: false,
			name: m.skill_jsts_name({}, opt),
			description: m.skill_jsts_description({}, opt),
			result: null,
		},
		{
			id: "python",
			slug: "jenkins-python-acrazie",
			group: "delivery",
			featured: false,
			name: m.skill_python_name({}, opt),
			description: m.skill_python_description({}, opt),
			result: null,
		},
		{
			id: "rust",
			slug: "jenkins-rust-acrazie",
			group: "delivery",
			featured: false,
			name: m.skill_rust_name({}, opt),
			description: m.skill_rust_description({}, opt),
			result: null,
		},
		{
			id: "symfony",
			slug: "jenkins-symfony-php-acrazie",
			group: "delivery",
			featured: false,
			name: m.skill_symfony_name({}, opt),
			description: m.skill_symfony_description({}, opt),
			result: null,
		},
	] as const;
}

export const skillsCatalog = {
	fr: createSkills("fr"),
	en: createSkills("en"),
} as const;
